/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car.gltf --transform
Author: autoNgraphic (https://sketchfab.com/autoNgraphic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-911-rauh-welt-0e1f5e1c0ddc4c3f88b8484461146a79
Title: Porsche 911 RAUH-Welt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group {...props} dispose={null} rotation={[0.02, Math.PI / 1.2, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.chassis_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.chassis_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.chassis_ok_silver_0.geometry} material={materials.silver} />
            <mesh geometry={nodes.chassis_ok_under_0.geometry} material={materials.under} />
            <mesh geometry={nodes.chassis_ok_vehicle_generic_doorshut__spec__0.geometry} material={materials.vehicle_generic_doorshut__spec} />
            <mesh geometry={nodes.chassis_ok_smod_racedetail_d__spec__0.geometry} material={materials.smod_racedetail_d__spec} />
            <mesh geometry={nodes.chassis_ok_glass_0.geometry} material={materials.glass} />
            <mesh geometry={nodes.chassis_ok_grill_0.geometry} material={materials.grill} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.interior_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.interior_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.interior_ok_silver_0.geometry} material={materials.silver} />
            <mesh geometry={nodes.interior_ok_alcantara_0.geometry} material={materials.alcantara} />
            <mesh geometry={nodes.interior_ok_symbols_0.geometry} material={materials.symbols} />
            <mesh geometry={nodes.interior_ok_leather_0.geometry} material={materials.leather} />
            <mesh geometry={nodes.interior_ok_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.interior_ok_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.interior_ok_mirror_0.geometry} material={materials.mirror} />
            <mesh geometry={nodes.interior_ok_carpet_0.geometry} material={materials.carpet} />
            <mesh geometry={nodes.interior_ok_gauges_0.geometry} material={materials.gauges} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.seats_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.seats_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.seats_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.seats_rwb_bride_0.geometry} material={materials.rwb_bride} />
            <mesh geometry={nodes.seats_carbontext_0.geometry} material={materials.carbontext} />
            <mesh geometry={nodes.seats_belt_0.geometry} material={materials.belt} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.carpet_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.carpet_ok_carpet911_0.geometry} material={materials.carpet911} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.rollcage_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.rollcage_chrome_0.geometry} material={materials.chrome} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.taillights_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.taillights_ok_lights_lod0__0.geometry} material={materials.lights_lod0} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.taillights_center_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.taillights_center_lights_lod0__0.geometry} material={materials.lights_lod0} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.side_skirts_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.side_skirts_ok_plastic_0.geometry} material={materials.plastic} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.movsteer_1_0_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.movsteer_1_0_rwbsteering_0.geometry} material={materials.rwbsteering} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.speedook_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.speedook_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.tahook_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.tahook_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.petrolok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.petrolok_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.oil_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.oil_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.temperature_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.temperature_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.hour_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.hour_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.minute_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.minute_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.ampers_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.ampers_red_0.geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.boot_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.boot_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.boot_ok_grill_0.geometry} material={materials.grill} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.boot_wing_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.boot_wing_ok_plastic_0.geometry} material={materials.plastic} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.bonnet_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.bonnet_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.bonnet_ok_tex_1157_0.geometry} material={materials.tex_1157} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.door_lf_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.door_lf_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.door_lf_ok_glass_0.geometry} material={materials.glass} />
            <mesh geometry={nodes.door_lf_ok_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.door_lf_ok_mirror_0.geometry} material={materials.mirror} />
            <mesh geometry={nodes.door_lf_ok_belt_0.geometry} material={materials.belt} />
            <mesh geometry={nodes.door_lf_ok_interior_diffuse_0.geometry} material={materials.interior_diffuse} />
            <mesh geometry={nodes.door_lf_ok_generic_leather_0.geometry} material={materials.generic_leather} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.door_rf_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.door_rf_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.door_rf_ok_glass_0.geometry} material={materials.glass} />
            <mesh geometry={nodes.door_rf_ok_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.door_rf_ok_mirror_0.geometry} material={materials.mirror} />
            <mesh geometry={nodes.door_rf_ok_belt_0.geometry} material={materials.belt} />
            <mesh geometry={nodes.door_rf_ok_interior_diffuse_0.geometry} material={materials.interior_diffuse} />
            <mesh geometry={nodes.door_rf_ok_generic_leather_0.geometry} material={materials.generic_leather} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.wing_rf_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.wing_rf_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.wing_rf_ok_comet_lights_0.geometry} material={materials.comet_lights} />
            <mesh geometry={nodes.wing_rf_ok_vehiclelights_0.geometry} material={materials.vehiclelights} />
            <mesh geometry={nodes.wing_rf_ok_vehiclelights128_0.geometry} material={materials.vehiclelights128} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.wing_lf_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.wing_lf_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.wing_lf_ok_comet_lights_0.geometry} material={materials.comet_lights} />
            <mesh geometry={nodes.wing_lf_ok_vehiclelights_0.geometry} material={materials.vehiclelights} />
            <mesh geometry={nodes.wing_lf_ok_vehiclelights128_0.geometry} material={materials.vehiclelights128} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.bump_front_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.bump_front_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.bump_front_ok_grill_0.geometry} material={materials.grill} />
            <mesh geometry={nodes.bump_front_ok_vehiclelights128_0.geometry} material={materials.vehiclelights128} />
            <mesh geometry={nodes.bump_front_ok_rwb_alpha_0.geometry} material={materials.rwb_alpha} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.bump_rear_ok_remap_0.geometry} material={materials.remap} />
            <mesh geometry={nodes.bump_rear_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.bump_rear_ok_grill_0.geometry} material={materials.grill} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.windscreen_ok_glass_0.geometry} material={materials.glass} />
            <mesh geometry={nodes.windscreen_ok_symbols_0.geometry} material={materials.symbols} />
            <mesh geometry={nodes.windscreen_ok_rwb_alpha_0.geometry} material={materials.rwb_alpha} />
            <mesh geometry={nodes.windscreen_ok_rwb_alpha2_0.geometry} material={materials.rwb_alpha2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.exhaust_ok_plastic_0.geometry} material={materials.plastic} />
            <mesh geometry={nodes.exhaust_ok_silver2_0.geometry} material={materials.silver2} />
            <mesh geometry={nodes.exhaust_ok_exhaust_0.geometry} material={materials.exhaust} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.wheel_brakes_0.geometry} material={materials.brakes} />
            <mesh geometry={nodes.wheel_ssr_0.geometry} material={materials.material_34} />
            <mesh geometry={nodes.wheel_tyre_0.geometry} material={materials.tyre} />
          </group>
          <mesh geometry={nodes.taillights_alpha_lights_lod0_alpha_0.geometry} material={materials.lights_lod0_alpha} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.bump_front_alpha_ok_vehiclelights_0.geometry} material={materials.vehiclelights} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
