/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 console.gltf --transform
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steam-deck-console-46e0c05675a7442dbe73f261436e6819
Title: Steam Deck console
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/console-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.shineuy_0.geometry} material={materials['steamDeckIMGShiney.png']} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials['steamDeckIMG.png']} />
        <mesh geometry={nodes.matt_0.geometry} material={materials['steamDeckIMG.png']} />
        <mesh geometry={nodes.emissive_0.geometry} material={materials['steamDeckIMGEmissive.png']} />
      </group>
    </group>
  )
}

useGLTF.preload('/console-transformed.glb')
