/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 notebook.gltf --transform
Author: _SeF_ (https://sketchfab.com/_SeF_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/notebook-b081286782c944f7a3bb3d8b93a7daf8
Title: Notebook
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/notebook-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.notebook_04_low_low_0.geometry} material={materials.material} position={[6.52, 27.9, -90.29]} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.notebook_01_low_low_0.geometry} material={materials.material} position={[6.52, 27.9, -90.29]} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.notebook_02_low_low_0.geometry} material={materials.material} position={[6.52, 27.9, -90.29]} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.notebook_03_low_low_0.geometry} material={materials.material} position={[6.52, 27.9, -90.29]} rotation={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/notebook-transformed.glb')